### ISSUE TITLE
examples -> createcredential.js error when scanning the code with the uPort app

### ISSUE THREAD

**Issue by lukigno95** [uport-project/uport-credentials#134]
# Current Behavior
Gives an error in the terminal.

# Expected Behavior
Shows in the terminal: Credential verified.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run createcredential.js in the example folder
2. Open the provided link
3. Scan with the android app the qr code showed in the browser

## Failure Logs/Screenshots
```
$ node createcredential.js 
Attestation Creator Service running, open at https://bec5ff87.ngrok.io
(node:31781) UnhandledPromiseRejectionWarning: Error: Signature invalid for JWT
    at verifyRecoverableES256K (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/did-jwt/lib/VerifierAlgorithm.js:60:22)
    at _callee2$ (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/did-jwt/lib/JWT.js:153:66)
    at tryCatch (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:31781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31781) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:31781) UnhandledPromiseRejectionWarning: Error: Signature invalid for JWT
    at verifyRecoverableES256K (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/did-jwt/lib/VerifierAlgorithm.js:60:22)
    at _callee2$ (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/did-jwt/lib/JWT.js:153:66)
    at tryCatch (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/node1/myTESTS/uportCredentialsTest/uport-credentials/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:31781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

```

**Comment by Eseoghene** [comment]
Thank you for reporting this issue we will get back to you shortly

**Comment by lukigno95** [comment]
Found the problem. I had to click con the mobile link... 
But I don't understand what was for the first qr showed, I mean if it wasn't for the mobile client for which client it was expected?
