### ISSUE TITLE
EthrDIDResolver requires a provider configuration for at least one network

### ISSUE THREAD

**Issue by eduardosanzb** [uport-project/uport-credentials#194]
**Describe the bug**
Following the demo, cannot instantiate a new Credentials object

**To Reproduce**
1. Install the latest `uport-credentials`
2. Create new indentity or use existent one.
3. Try to instantiate a `new Credentials`

Following the types I can see that the Networks object follow a structure. But I was unable to find an example.
```
interface Network {
    registry: string;
    rpcUrl: string;
}
interface Networks {
    [net: string]: Network;
}
interface Settings {
    ...
    networks?: Networks;
    ...
}
```

**Expected behavior**
Continue with the demo

**Screenshots**
```
/Users/Projects/SSI/uport/playing-with-jwtvc/node_modules/uport-credentials/node_modules/ethr-did-resolver/dist/ethr-did-resolver.js:1
function t(t){return t&&"object"==typeof t&&"default"in t?t.default:t}var i=t(require("ethjs-provider-http")),e=t(require("ethjs-query")),n=t(require("ethjs-abi")),r=t(require("ethjs-contract")),h=require("buffer");const o=function(){function t(){}return t.prototype.then=function(i,e){const n=new t,r=this.s;if(r){const t=1&r?i:e;if(t){try{s(n,1,t(this.v))}catch(t){s(n,2,t)}return n}return this}return this.o=function(t){try{const r=t.v;1&t.s?s(n,1,i?i(r):r):e?s(n,1,e(r)):s(n,2,r)}catch(t){s(n,2,t)}},n},t}();function s(t,i,e){if(!t.s){if(e instanceof o){if(!e.s)return void(e.o=s.bind(null,t,i));1&i&&(i=e.s),e=e.v}if(e&&e.then)return void e.then(s.bind(null,t,i),s.bind(null,t,2));t.s=i,t.v=e;const n=t.o;n&&n(t)}}function a(t){return t instanceof o&&1&t.s}"undefined"!=typeof Symbol&&(Symbol.iterator||(Symbol.iterator=Symbol("Symbol.iterator"))),"undefined"!=typeo

Error: EthrDIDResolver requires a provider configuration for at least one network
    at /Users/Projects/SSI/uport/playing-with-jwtvc/node_modules/uport-credentials/node_modules/ethr-did-resolver/dist/ethr-did-resolver.js:1:51835
    at Object.getResolver (/Users/Projects/SSI/uport/playing-with-jwtvc/node_modules/uport-credentials/node_modules/ethr-did-resolver/dist/ethr-did-resolver.js:1:51923)
    at new f (/Users/Projects/SSI/uport/playing-with-jwtvc/node_modules/uport-credentials/lib/index.js:1:1962)
    at Object.<anonymous> (/Users/Projects/SSI/uport/playing-with-jwtvc/dist/index.js:58:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

**Desktop (please complete the following information):**
 - OS: Macos Mojave

**Comment by mirceanis** [comment]
@eduardosanzb Did you try [the configuration block mentioned in the readme](https://github.com/uport-project/uport-credentials#uport-credentials-library)?

What demo are you following specifically?
The change to the configuration requirements regarding ethr-did-resolver are probably not reflected in every doc piece that was published. It would be helpful if you linked to the demo code that you are following which appears to be showing the older code.

**Comment by eduardosanzbBCG** [comment]
@mirceanis Thank you for the response,
Indeed we found the configuration [in the readme, as you mentioned](https://github.com/uport-project/uport-credentials#uport-credentials-library).

I tried to follow the demo from the following sources:

* [developer portal](https://developer.uport.me/uport-credentials/index#create-request-attested-data)
* And also an outdated one (potentially), the snippets of code that are part of the [Dashboard](https://developer.uport.me/myapps/detail) in the `code` tab.

Thank you.

**Comment by eduardosanzbBCG** [comment]
Do you guys have a chat rocket.chat/slack or similar?
Regards

**Comment by mirceanis** [comment]
> Do you guys have a chat rocket.chat/slack or similar?

The preferred support channel is through [support.uport.me](https://support.uport.me/hc/en-us)
There is also a [community gitter chat](https://gitter.im/uport-project/Lobby) but we do not have the manpower to answer there very often during these times.

Please close this issue you managed to apply the suggested configuration.

**Comment by mirceanis** [comment]
Closing this for lack of activity, please reopen if it is still an issue.
